# Generated by Django 3.0.6 on 2020-05-13 20:58

from django.db import migrations, models
import payments.models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20200511_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_day',
            field=payments.models.IntegerRangeField(blank=True, null=True),
        ),
    ]
