# Generated by Django 3.0.6 on 2020-05-13 21:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_auto_20200513_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_day',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
